server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://10.150.1.15:3306/activiti?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true&nullCatalogMeansCurrent=true
    username: root
    password: zzyt@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  activiti:
    # 自动部署验证设置:true-开启（默认）、false-关闭
    check-process-definitions: false
    db-identity-used: true
    # 自动生成Activiti相关表 第一次生成后建议关闭提高运行速度
    database-schema-update: false
    # 保存历史数据级别设置为full最高级别，便于历史数据的追溯
    history-level: full
    async-executor-activate: false
